[settings]
allow_nsfw = false
theme = "dark"
times_to_run = 1
opacity = 0.9
transition = 0.2
storymode = true

[settings.background]
background_choice = "minecraft"

[settings.tts]
aws_polly_voice = "Matthew"
streamlabs_polly_voice = "Matthew"
tiktok_voice = "en_us_006"
python_voice = "1"
py_voice_num = "2"
voice_choice = "streamlabspolly"

[reddit.creds]
2fa = false

[reddit.thread]
random = false
subreddit = "AskReddit"
post_id = ""
max_comment_length = 500
min_comments = 50
post_lang = ""
