name: CD

on: [pull_request, workflow_dispatch]

jobs:
  make-video:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup
        shell: bash
        env:
          SUPER_SECRET: ${{ secrets.NOT_TELLING }}
        run: |
          pip install -r requirements.txt
          python -m playwright install
          python -m playwright install-deps
          sed -i '/reddit.creds/a \$SUPER_SECRET' config.toml
      - name: make video
        run: |
          python main.py
          echo hi
